import * as images from "public/cards";

const WomanImageDict: any = {
  adaLovelace: images.AdaLoveLace,
  adrianeParraga: images.AdrianneParraga,
  adrianaNeumann: images.AdrianaNeumann,
  alexandraElbakyan: images.AlexandraElbakyan,
  anaChies: images.AnaChies,
  barbaraLiskov: images.BarbaraLiskov,
  camilaAchutti: images.CamilaAchutti,
  carlaDalSasso: images.CarlaDalSasso,
  carolShaw: images.CarolShaw,
  ceciliaBaranauskas: images.CeciliaBaranauskas,
  clarisseSieckenius: images.ClarisseSieckenius,
  cynthiaBreazeal: images.CynthiaBreazeal,
  deboraMatos: images.DeboraMatos,
  edithClarke: images.EdithClarke,
  edithRanzini: images.EdithRanzini,
  edithStoney: images.EdithStoney,
  emilieDuChatelet: images.EmilieDuChatelet,
  emilyRoebling: images.EmilyRoebling,
  emmyNoether: images.EmmyNoether,
  enedinaMarques: images.EnedinaMarques,
  ethelWihelm: images.EthelWihelm,
  fabriciaDamando: images.FabriciaDamando,
  fernandaGusmao: images.FernandaGusmao,
  francesAllen: images.FrancesAllen,
  gladysWest: images.GladysWest,
  hedyLamarr: images.HedyLamarr,
  herthaMarks: images.HerthaMarks,
  isabelleStone: images.IsabelleStone,
  julianaRotich: images.JulianaRotich,
  karenUhlenbeck: images.KarenUhlenbeck,
  katieBouman: images.KatieBouman,
  kirstineBjerrum: images.KirstineBjerrum,
  leticiaGuimaraes: images.LeticiaGuimaraes,
  lianeTarouco: images.LianeTarouco,
  liseMeitner: images.LiseMeitner,
  maChungPei: images.MaChungPei,
  marcelleSoares: images.MarcelleSoares,
  marciaBarbosa: images.MarciaBarbosa,
  margaretHamilton: images.MargaretHamilton,
  margritKrug: images.MargritKrug,
  mariaKlawe: images.MariaKlawe,
  mariaTelkes: images.MariaTelkes,
  mariettaBlau: images.MariettaBlau,
  maryamMirzakhani: images.MaryamMirzakhani,
  maryKenneth: images.MaryKenneth,
  philippaFawcett: images.PhilippaFawcett,
  radiaPerlman: images.RadiaPerlman,
  raquelGiulian: images.RaquelGiulian,
  rosaMariaVicari: images.RosaMariaVicari,
  sonjaAshauer: images.SonjaAshauer,
  sophieGermain: images.SophieGermain,
  taniaCabral: images.TaniaCabral,
  terriAttwood: images.TerriAttwood,
  thaisaBergmann: images.ThaisaBergmann,
  veronicaDahl: images.VeronicaDahl,
};

export default WomanImageDict;
