import { Metadata } from "next"
import { env } from "env.mjs"

export const keywords = [
  "IncludeGurias",
  "Include Gurias",
  "#IncludeGurias",
  "#Include Gurias",
  "#Include <Gurias>",
  "#include gurias",
  "Meninas Digitais",
  "Meninas Digitais include gurias",
  "STEM para meninas",
  "Tecnologia para meninas",
  "Engenharia para meninas",
  "Matemática para meninas",
  "Desenvolvimento do Pensamento Computacional",
  "Programação para meninas",
  "Oficinas de programação",
  "Oficinas de robótica para meninas",
  "Inclusão de meninas na tecnologia",
  "Inspiração para mulheres na tecnologia",
  "Superando barreiras na STEM",
  "Mulheres na ciência",
  "Inovação tecnológica",
  "Cursos STEM para meninas",
  "Encontros de tecnologia para mulheres",
  "Motivação em STEM",
  "Desenvolvimento do raciocínio lógico para crianças",
  "Inclusão de gênero na tecnologia",
  "Potencial feminino em tecnologia",
  "Projeto STEM para meninas",
  "Meninos e meninas na tecnologia",
  "Participação feminina em STEM",
  "Estímulo à criatividade em tecnologia",
  "Empoderamento feminino em tecnologia",
  "Projetos educacionais em STEM",
  "SCEO",
  "SCEO Projeto Include Gurias",
  "SCEO STEM",
  "Inovação educacional em tecnologia",
  "Desenvolvimento de habilidades em STEM",
  "Ensino fundamental STEM",
  "Encontros de inovação",
  "Promovendo a diversidade em tecnologia",
  "Mulheres e tecnologia",
  "Troca de ideias em tecnologia",
  "Relatos de superação em STEM",
  "Potencial feminino em STEM",
  "Meninos também são bem-vindos em STEM",
  "Oficinas de ciência para meninas",
  "Capacitação tecnológica feminina",
  "Desenvolvimento de competências em tecnologia",
  "Educação STEM",
  "Mulheres na área tecnológica",
  "Despertando o interesse por STEM",
  "Aprendizado colaborativo em STEM",
  "Diversidade de gênero em STEM",
  "Capacitação em STEM",
  "Projeto educacional de tecnologia",
  "Inclusão de meninas na inovação tecnológica",
  "Oficinas de tecnologia para meninas",
  "Oficinas de tecnologia para crianças",
  "Meninas na tecnologia",
  "Meninas empoderadas",
  "Meninas na ciência",
  "Meninas na engenharia",
  "Meninas na matemática",
  "Meninas na programação",
  "Meninas na robótica",
]

const baseMetadata: Metadata = {
  title: "Include Gurias",
  description: "Aqui você encontra tudo sobre o projeto Include Gurias",
  applicationName: "Include Gurias",
  publisher: "Bots Channel",
  authors: [
    {
      name: "Lucas Henrique Diniz Ostroski",
      url: "https://www.linkedin.com/in/lucas-diniz-ostroski/",
    },
    { name: "Bots Channel", url: "https://www.botschannel.com//" },
  ],
  creator: "Bots Channel, Lucas Henrique Diniz Ostroski",
  keywords: keywords,
  openGraph: {
    title: "Include Gurias",
    description: "Aqui você encontra tudo sobre o projeto Include Gurias",
    url: `${env.SITE_URL}/`,
    type: "website",
    siteName: "Include Gurias",
    images: [
      {
        url: "public/metadata/main.png",
      },
    ],
  },
  twitter: {
    site: "@includegurias",
    card: "summary_large_image",
    creator: "@lucasostroski",
    title: "Include Gurias",
    description: "Aqui você encontra tudo sobre o projeto Include Gurias",
    images: "public/metadata/main.png",
  },

  metadataBase: new URL(env.SITE_URL), // Assuming env.SITE_URL holds your base URL
}

export default baseMetadata
