import { Metadata } from "next";

export const keywords = [
  "IncludeGurias",
  "Include Gurias",
  "#IncludeGurias",
  "#Include Gurias",
  "#Include <Gurias>",
  "#include gurias",
  "Meninas Digitais",
  "Meninas Digitais include gurias",
  "STEM para meninas",
  "Tecnologia para meninas",
  "Engenharia para meninas",
  "Matemática para meninas",
  "Desenvolvimento do Pensamento Computacional",
  "Programação para meninas",
  "Oficinas de programação",
  "Oficinas de robótica para meninas",
  "Inclusão de meninas na tecnologia",
  "Inspiração para mulheres na tecnologia",
  "Superando barreiras na STEM",
  "Mulheres na ciência",
  "Inovação tecnológica",
  "Cursos STEM para meninas",
  "Encontros de tecnologia para mulheres",
  "Motivação em STEM",
  "Desenvolvimento do raciocínio lógico para crianças",
  "Inclusão de gênero na tecnologia",
  "Potencial feminino em tecnologia",
  "Projeto STEM para meninas",
  "Meninos e meninas na tecnologia",
  "Participação feminina em STEM",
  "Estímulo à criatividade em tecnologia",
  "Empoderamento feminino em tecnologia",
  "Projetos educacionais em STEM",
  "SCEO",
  "SCEO Projeto Include Gurias",
  "SCEO STEM",
  "Inovação educacional em tecnologia",
  "Desenvolvimento de habilidades em STEM",
  "Ensino fundamental STEM",
  "Encontros de inovação",
  "Promovendo a diversidade em tecnologia",
  "Mulheres e tecnologia",
  "Troca de ideias em tecnologia",
  "Relatos de superação em STEM",
  "Potencial feminino em STEM",
  "Meninos também são bem-vindos em STEM",
  "Oficinas de ciência para meninas",
  "Capacitação tecnológica feminina",
  "Desenvolvimento de competências em tecnologia",
  "Educação STEM",
  "Mulheres na área tecnológica",
  "Despertando o interesse por STEM",
  "Aprendizado colaborativo em STEM",
  "Diversidade de gênero em STEM",
  "Capacitação em STEM",
  "Projeto educacional de tecnologia",
  "Inclusão de meninas na inovação tecnológica",
  "Oficinas de tecnologia para meninas",
  "Oficinas de tecnologia para crianças",
  "Meninas na tecnologia",
  "Meninas empoderadas",
  "Meninas na ciência",
  "Meninas na engenharia",
  "Meninas na matemática",
  "Meninas na programação",
  "Meninas na robótica",
];

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://includegurias.com.br";

const baseMetadata: Metadata = {
  title: {
    default: "Include Gurias - Garotas que codam mudam o mundo",
    template: "%s | Include Gurias",
  },
  description:
    "Projeto Include Gurias: Despertando o interesse de meninas na área STEM através do desenvolvimento do pensamento computacional. Oficinas de programação, robótica e tecnologia para empoderar mulheres na ciência.",
  applicationName: "Include Gurias",
  publisher: "Include Gurias",
  authors: [
    {
      name: "Lucas Henrique Diniz Ostroski",
      url: "https://www.linkedin.com/in/lucas-diniz-ostroski/",
    },
  ],
  creator: "Lucas Henrique Diniz Ostroski",
  keywords: keywords,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
  manifest: "/site.webmanifest",
  openGraph: {
    title: "Include Gurias - Garotas que codam mudam o mundo",
    description:
      "Projeto Include Gurias: Despertando o interesse de meninas na área STEM através do desenvolvimento do pensamento computacional.",
    url: `${SITE_URL}`,
    siteName: "Include Gurias",
    locale: "pt_BR",
    type: "website",
    images: [
      {
        url: `${SITE_URL}/metadata/main.png`,
        width: 1200,
        height: 630,
        alt: "Include Gurias - Projeto STEM para meninas",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@includegurias",
    creator: "@includegurias",
    title: "Include Gurias - Garotas que codam mudam o mundo",
    description:
      "Projeto Include Gurias: Despertando o interesse de meninas na área STEM através do desenvolvimento do pensamento computacional.",
    images: [`${SITE_URL}/metadata/main.png`],
  },
  metadataBase: new URL(SITE_URL),
  alternates: {
    canonical: `${SITE_URL}`,
  },
  category: "education",
  classification: "STEM Education",
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
};

export default baseMetadata;
